
on: [push, pull_request]

jobs:
  checkout_code:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Save repository's content as artifact
      uses: actions/upload-artifact@v3
      with:
        name: repo
        path: ${{ github.workspace }}

  v18:
    runs-on: ubuntu-22.04
    needs: checkout_code
    container:
      image: "node:18-buster"
    steps:
      - name: Install sudo & git
        run: |
          apt update
          apt install -y sudo 
          sudo apt install -y git
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'
      - name: Get repository's content
        uses: actions/download-artifact@v3
        with:
          name: repo
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: v1-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-dependencies-${{ hashFiles('**/yarn.lock') }}
            v1-dependencies-
      - name: Update yarn
        run: |
          node -v
          yarn global add yarn@latest
      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Install @commitlint/test
        run: npm i @commitlint/test
      - name: Test
        run: yarn test-ci
