name: CI

on: [push, pull_request]

jobs:
  v14:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - name: Install sudo
        run: |
          apt update
          apt install --yes sudo
      - name: Install node
        run: |
          sudo apt install --yes curl
          # can't install ubuntu's default nodejs version because we would get this error:
          # error @jest/core@29.4.1: The engine "node" is incompatible with this module. Expected version "^14.15.0 || ^16.10.0 || >=18.0.0". Got "12.22.9"
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes nodejs
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v2
      - name: Update yarn
        run: |
          node --version
          yarn global add yarn@latest
      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Test
        run: yarn test-ci

  v16:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - name: Install sudo
        run: |
          apt update
          apt install --yes sudo
      - name: Install node
        run: |
          sudo apt install --yes curl
          # can't install ubuntu's default nodejs version because we would get this error:
          # error @jest/core@29.4.1: The engine "node" is incompatible with this module. Expected version "^14.15.0 || ^16.10.0 || >=18.0.0". Got "12.22.9"
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes nodejs
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v2
      - name: Update yarn
        run: |
          node --version
          yarn global add yarn@latest
      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Test
        run: yarn test-ci

  v18:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - name: Install sudo
        run: |
          apt update
          apt install --yes sudo
      - name: Install node
        run: |
          sudo apt install --yes curl
          # can't install ubuntu's default nodejs version because we would get this error:
          # error @jest/core@29.4.1: The engine "node" is incompatible with this module. Expected version "^14.15.0 || ^16.10.0 || >=18.0.0". Got "12.22.9"
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes nodejs
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v2
      - name: Update yarn
        run: |
          node --version
          yarn global add yarn@latest
      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Test
        run: yarn test-ci

  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Update yarn
        run: |
          node --version
          yarn global add yarn@latest
      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Test
        run: yarn test-ci
