name: CI

on: [push, pull_request]

jobs:
  v14:
    runs-on: ubuntu-22.04
    container:
      image: "node:14-buster"
    steps:
      - name: Install sudo
        run: |
          apt update
          apt install --yes sudo
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v2
      - name: Update yarn
        run: |
          node --version
          yarn global add yarn@latest
      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Test
        run: yarn test-ci

  v16:
    runs-on: ubuntu-22.04
    container:
      image: "node:16-buster"
    steps:
      - name: Install sudo
        run: |
          apt update
          apt install --yes sudo
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v2
      - name: Update yarn
        run: |
          node --version
          yarn global add yarn@latest
      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Test
        run: yarn test-ci

  v18:
    runs-on: ubuntu-22.04
    container:
      image: "node:18-buster"
    steps:
      - name: Install sudo
        run: |
          apt update
          apt install --yes sudo
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v2
      - name: Update yarn
        run: |
          node --version
          yarn global add yarn@latest
      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Test
        run: yarn test-ci

  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Update yarn
        run: |
          node --version
          yarn global add yarn@latest
      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Test
        run: yarn test-ci
